### ISSUE TITLE
Make column variable format in prompt `{{ var }}` instead of `{ var }`

### ISSUE THREAD

**Issue by benjaminye** [georgian-io/LLM-Finetuning-Toolkit#153]
This improves user experience when desire output is json

E.g.
```yaml
prompt_stub:
  >-
  {
    "foo": {col_1},
    "bar": {col_2}
  }
```

The current approach would not work as we're capturing everything inside `{}`
